### ISSUE TITLE
"encrypted"体现在哪里？

### ISSUE THREAD

**Issue by briteming** [li-plus/secure-socks#1]
hi

你说“A mini encrypted socks tunnel to bypass the firewall.”。不过"encrypted"体现在哪里？

**Comment by li-plus** [comment]
Hi, local和server之间会使用一个代换密码表对每个字节进行加密传输，理论上并非绝对安全，但用来混淆GFW已经足够了。安全性通常需要由端到端加密的协议来保证，例如SSL/TLS及其上层协议，我们不保证用隧道传输明文信息的安全性，只负责混淆。
